#!/bin/bash
# =============================================================================
# init.sh — Container initialization script
# =============================================================================
# Runs BEFORE supervisord starts. Performs:
#   1. Sets timezone to Asia/Tehran (overridable via $TZ)
#   2. Generates admin password if not provided
#   3. Configures 3x-ui credentials & panel port via the x-ui CLI
#   4. Imports the Xray template config (config.json) into the panel DB
#   5. Persists credentials to /etc/x-ui/admin-credentials.txt for recovery
#   6. Hands off to the main CMD (supervisord)
# =============================================================================
set -euo pipefail

# ---------- Helpers ----------------------------------------------------------
log()  { echo "[init] $*"; }
warn() { echo "[init] WARNING: $*" >&2; }

# ---------- Step 1: Timezone -------------------------------------------------
export TZ="${TZ:-Asia/Tehran}"
if [ -f "/usr/share/zoneinfo/${TZ}" ]; then
    ln -fs "/usr/share/zoneinfo/${TZ}" /etc/localtime
    echo "${TZ}" > /etc/timezone
    log "Timezone set to ${TZ}"
else
    warn "Timezone file for ${TZ} not found — using container default."
fi

# ---------- Step 2: Paths & credentials --------------------------------------
X_UI_BIN="/usr/local/x-ui/x-ui"
DB_PATH="/etc/x-ui/x-ui.db"
DB_DIR="$(dirname "$DB_PATH")"
mkdir -p "$DB_DIR" /var/log/xray /var/log/nginx /var/log/supervisor

ADMIN_USER="${ADMIN_USERNAME:-admin}"

if [ -z "${ADMIN_PASSWORD:-}" ]; then
    ADMIN_PASSWORD="$(openssl rand -hex 12)"
    echo ""
    echo "=========================================================="
    echo "  3x-ui ADMIN PASSWORD AUTO-GENERATED"
    echo "  --------------------------------------"
    echo "  Username : ${ADMIN_USER}"
    echo "  Password : ${ADMIN_PASSWORD}"
    echo "  --------------------------------------"
    echo "  (Saved to /etc/x-ui/admin-credentials.txt in container)"
    echo "=========================================================="
    echo ""
else
    log "Using ADMIN_PASSWORD from environment variable."
fi

PANEL_PORT="${PANEL_PORT:-2053}"

# ---------- Step 3: Configure 3x-ui via CLI ----------------------------------
log "Configuring 3x-ui (username, password, port=${PANEL_PORT})..."

# These commands read/write the SQLite DB at /etc/x-ui/x-ui.db directly.
# They are safe to run on every container start (idempotent).
"$X_UI_BIN" setting -username "$ADMIN_USER" -password "$ADMIN_PASSWORD" 2>&1 || warn "x-ui setting -username/-password failed (DB may already be configured)."
"$X_UI_BIN" setting -port "$PANEL_PORT" 2>&1 || warn "x-ui setting -port failed."

# Set a non-default panel web base path (optional hardening)
# "$X_UI_BIN" setting -webBasePath "/panel-" 2>&1 || true

# ---------- Step 4: Import Xray template config ------------------------------
if [ -f "/etc/x-ui/config-template.json" ]; then
    log "Importing Xray template config from /etc/x-ui/config-template.json..."
    "$X_UI_BIN" setting -xrayTemplateConfig /etc/x-ui/config-template.json 2>&1 || warn "Could not import Xray template config via CLI — panel will use its built-in default."
fi

# ---------- Step 5: Persist credentials for recovery -------------------------
cat > /etc/x-ui/admin-credentials.txt <<EOF
# ============================================================
#  3x-ui Admin Credentials (generated by init.sh)
#  Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')
# ============================================================
#  Access URL : https://<your-defang-domain>/
#  Username   : ${ADMIN_USER}
#  Password   : ${ADMIN_PASSWORD}
#  Panel Port : ${PANEL_PORT} (internal, behind Nginx on :80)
# ============================================================
#  VLESS-WS path : /vless-ws/   (internal Xray port 10001)
#  Trojan-WS path: /trojan-ws/  (internal Xray port 10002)
# ============================================================
EOF
chmod 600 /etc/x-ui/admin-credentials.txt
log "Credentials saved to /etc/x-ui/admin-credentials.txt"

# ---------- Step 6: Pre-seed a default VLESS-WS inbound (best-effort) -------
# This makes the deployment usable immediately. Users can edit/delete it
# from the panel UI afterwards. We use sqlite3 directly because the x-ui CLI
# does not expose an "add inbound" command.
log "Attempting to pre-seed a default VLESS-WS inbound..."
if command -v sqlite3 >/dev/null 2>&1 && [ -f "$DB_PATH" ]; then
    # Generate a fresh UUID for the default client
    DEFAULT_UUID="$(cat /proc/sys/kernel/random/uuid 2>/dev/null || openssl rand -hex 16 | sed 's/\(.\{8\}\)\(.\{4\}\)\(.\{4\}\)\(.\{4\}\)/\1-\2-\3-\4-/')"
    DEFAULT_SUBID="$(openssl rand -hex 8)"

    VLESS_SETTINGS='{"clients":[{"id":"'"$DEFAULT_UUID"'","flow":"","email":"default-user","limitIp":0,"totalGB":0,"expiryTime":0,"enable":true,"tgId":"","subId":"'"$DEFAULT_SUBID"'","reset":0}],"decryption":"none","fallbacks":[{"dest":"127.0.0.1:8080","xver":1}]}'
    VLESS_STREAM='{"network":"ws","security":"none","wsSettings":{"path":"/vless-ws/","headers":{}}}'
    VLESS_SNIFF='{"enabled":true,"destOverride":["http","tls","quic"],"metadataOnly":false}'

    # Insert only if an inbound on port 10001 does not already exist
    sqlite3 "$DB_PATH" \
        "INSERT OR IGNORE INTO inbounds (user_id, up, down, total, remark, enable, expiry_time, listen, port, protocol, settings, stream_settings, tag, sniffing)
         SELECT 1, 0, 0, 0, 'VLESS-WS-Default', 1, 0, '127.0.0.1', 10001, 'vless',
                '${VLESS_SETTINGS}', '${VLESS_STREAM}', 'vless-ws-inbound', '${VLESS_SNIFF}'
         WHERE NOT EXISTS (SELECT 1 FROM inbounds WHERE port=10001);" 2>&1 && \
        log "Default VLESS-WS inbound ready (UUID: ${DEFAULT_UUID})" || \
        warn "Could not pre-seed inbound — add it manually from the panel UI."
else
    warn "sqlite3 not available or DB not found — skip pre-seeding. Add inbound from panel UI."
fi

# ---------- Step 7: Hand off to supervisord ----------------------------------
log "Initialization complete. Starting supervisord (Nginx + 3x-ui)..."
exec "$@"
